pipeline {
    agent any

    tools {
        maven "maven-3.8.1"
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t springboot-first-app-dockerized1 .'
            }
        }
        stage('Deliver') { 
            steps {
                sh 'docker run -p 2223:2223 springboot-first-app-dockerized1'
            }
        }
    }
}