pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t fokamdk99/springboot-first-app springboot-first-app/Dockerfile'
            }
        }
        stage('Deliver') { 
            steps {
                sh 'docker run -p 2223:2223 fokamdk99/springboot-first-app'
            }
        }
    }
}