pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker build -f springboot-first-app/Dockerfile -t fokamdk99/springboot-first-app .'
            }
        }
        stage('Deliver') { 
            steps {
                sh 'docker run -p 2223:2223 fokamdk99/springboot-first-app'
            }
        }
    }
}